/* Datos curados a partir del documento GT Cultura Oceánica (CONA), Acción 4 - Portal Cultura Oceánica */

const RESOURCE_CATEGORIES = [
  {
    id: "historia",
    title: "Cultura oceánica: historia, estructura y definición",
    intro: "Documentos base que definen qué es la alfabetización oceánica y cómo se estructura como campo.",
    items: [
      { label: "Science content and standards for Ocean Literacy — Cava, Schoedinger, Strang & Tuddenham (2005)", url: "https://www.coexploration.org/oceanliteracy/documents/OLit2004-05_Final_Report.pdf" },
      { label: "Ocean Literacy Scope and Sequence for Grades K-12 — NMEA (2010)", url: "https://www.marine-ed.org/ocean-literacy/special-report" },
      { label: "Cultura oceánica para todos, Kit pedagógico — UNESCO (2018)", url: "https://unesdoc.unesco.org/ark:/48223/pf0000263062" },
      { label: "Ocean Literacy: The Essential Principles — NOAA, versión 3.1 (2021)", url: "https://static1.squarespace.com/static/5b4cecfde2ccd188cfed8026/t/60b90193ec346816a95717bb/1622737304272/OceanLiteracy_ENG_V3.1_2021.pdf" },
      { label: "Ocean Literacy within the UN Decade — Framework for Action, IOC-UNESCO (2021)", url: "https://unesdoc.unesco.org/ark:/48223/pf0000377708" },
      { label: "A Handbook for Increasing Ocean Literacy — NMEA (2021)", url: "https://www.marine-ed.org/ocean-literacy/handbook" },
      { label: "A New Blue Curriculum: toolkit for policy-makers — UNESCO/IOC (2022)", url: "https://unesdoc.unesco.org/ark:/48223/pf0000380544" },
      { label: "State-of-the-art of Ocean Literacy — UNESCO/IOC (2022)", url: "https://unesdoc.unesco.org/ark:/48223/pf0000382663" },
    ],
  },
  {
    id: "decada",
    title: "Década de las Ciencias Oceánicas 2021-2030",
    items: [
      { label: "Resolución Asamblea ONU A/RES/72/73 (2017)", url: "https://documents-dds-ny.un.org/doc/UNDOC/GEN/N17/421/94/PDF/N1742194.pdf?OpenElement" },
      { label: "La ciencia que necesitamos para el océano que queremos — UNESCO/COI (2019)", url: "https://www.un.org/sites/un2.un.org/files/2020/05/brochure_spanish.pdf" },
      { label: "Programas Oceánicos de la UNESCO", url: "https://unesdoc.unesco.org/ark:/48223/pf0000381648_spa" },
      { label: "Portal UNESCO/COI · Década de las Ciencias Oceánicas", url: "https://www.oceandecade.org/" },
      { label: "Portal UNESCO/COI · Cultura Oceánica", url: "https://oceanliteracy.unesco.org/" },
      { label: "Portal COEXPLORATION", url: "http://oceanliteracy.wp2.coexploration.org/" },
    ],
  },
  {
    id: "investigacion",
    title: "Trabajos de investigación en Chile",
    items: [
      { label: "Proyecto de Investigación “Chile y su Mar” — Instituto de Sociología PUC, Revista de Marina (1989)", url: "https://revistamarina.cl/revistas/1989/2/faguirreb%20-%20hgodoyu.pdf" },
      { label: "Alfabetización Oceánica: ¿Qué saben los estudiantes chilenos sobre el mar? — Congreso Ciencias del Mar (2016)", url: "https://www.schcm.cl/images/biblioteca/036.pdf" },
      { label: "Conectando el Océano con las Aulas — Congreso Ciencias del Mar (2017)", url: "https://www.schcm.cl/images/biblioteca/037.pdf" },
      { label: "¿Funcionan nuestros proyectos de educación marina? Programa Chile es Mar — CCM (2017)", url: "https://www.schcm.cl/images/biblioteca/037.pdf" },
      { label: "Red de Docentes Oceánicos: una experiencia colaborativa — CCM", url: "https://www.schcm.cl/images/biblioteca/038.pdf" },
      { label: "Línea Base: ¿sobre qué construir la educación marina en Chile? — CCM (2018)", url: "https://www.schcm.cl/images/biblioteca/038.pdf" },
      { label: "Cultura Oceánica y Alfabetización Marina para Chile. Una propuesta — Revista de Marina (2020)", url: "https://revistamarina.cl/es/articulo/cultura-oceanica-y-alfabetizacion-marina-para-chile-una-propuesta" },
      { label: "Alfabetización oceánica en adolescentes de San Antonio — Revista Brotes Científicos (2020)", url: "https://brotescientificos.usach.cl/wp-content/uploads/2021/07/v4n2a2020_v1_Revista.pdf" },
      { label: "Academia de Exploradores Marinos: Espacio Virtual de Aprendizaje — CCM (2021)", url: "https://www.schcm.cl/images/biblioteca/040.pdf" },
      { label: "El Camino del Pirata: juego para la educación marina familiar — CCM (2021)", url: "https://www.schcm.cl/images/biblioteca/040.pdf" },
      { label: "Fanzines para comunicar Ciencia Marina — CCM (2021)", url: "https://www.schcm.cl/images/biblioteca/040.pdf" },
      { label: "Chilemio Navega: divulgación científica a la realidad local — CCM (2021)", url: "https://www.schcm.cl/images/biblioteca/040.pdf" },
      { label: "Los libros y guías informativas como recursos de divulgación — CCM (2021)", url: "https://www.schcm.cl/images/biblioteca/040.pdf" },
      { label: "Programa de Alfabetización Marina — CCM (2022)", url: "https://www.schcm.cl/images/biblioteca/Libro%20de%20Resumenes_XLICCM_2022.pdf" },
      { label: "Estrategia y Plan de Acción de Cultura Oceánica y Alfabetización Marina — Revista Mar (2021)", url: "https://www.ligamar.cl/files/archivos/revista_mar_2021.pdf" },
      { label: "Alfabetización oceánica y conexión con el océano en Chile — Rev. U. Autónoma (2022)", url: "https://revistas.uautonoma.cl/index.php/scr/article/view/1795" },
      { label: "El mar como eje vertebrador de aprendizajes en la primera infancia — Tesis, U. de Valparaíso", url: null },
      { label: "¿Cómo está representado el océano en textos escolares chilenos? — Ocean and Coastal Research (2023)", url: null },
      { label: "Rol de las juventudes en la educación marina en Latinoamérica y el Caribe — CCM (2023)", url: null },
      { label: "¿Cómo se visualiza el mar en los textos escolares en Chile? — CCM (2023)", url: null },
    ],
  },
  {
    id: "normativa",
    title: "Normativa nacional, políticas, planes y estrategias",
    items: [
      { label: "Política Oceánica Nacional de Chile — D.S. N°74/2018, MINREL", url: "https://www.bcn.cl/leychile/navegar?idNorma=1118403" },
      { label: "Plan Oceanográfico Nacional 2021-2030", url: "http://www.cona.cl/pub/plan_oce_nac_es.pdf" },
      { label: "Estrategia Nacional de la Biodiversidad 2017-2030", url: "https://mma.gob.cl/wp-content/uploads/2018/03/Estrategia_Nac_Biodiv_2017_30.pdf" },
      { label: "Estrategia de Cambio Climático de Largo Plazo al 2025", url: "https://cambioclimatico.mma.gob.cl/wp-content/uploads/2021/11/ECLP-LIVIANO.pdf" },
      { label: "Política Antártica de Chile (2021)", url: "https://www.minrel.gob.cl/minrel/site/docs/20190906/20190906113642/3a___texto_politica_antarticanacional_de_2021__aprobada_16_3_2021.pdf" },
      { label: "Estatuto Antártico Chileno", url: "https://www.bcn.cl/leychile/navegar?idNorma=1149631" },
      { label: "Mares de Chile: Visión 2040", url: "https://biblioteca.digital.gob.cl/handle/123456789/3940" },
      { label: "Estrategia Administración Marítima de Chile (2020)", url: "https://www.directemar.cl/directemar/site/docs/20220125/20220125163404/estrategia_general_.pdf" },
      { label: "Política Oceánica — Instituto de Estudios Internacionales, U. de Chile (1977)", url: "https://libros.uchile.cl/313" },
      { label: "Bases para una Política Oceánica Nacional — Armada de Chile (1994)", url: "https://revistamarina.cl/revistas/1994/3/jmartinezb.pdf" },
      { label: "Ley General de Pesca y Acuicultura", url: "https://www.subpesca.cl/portal/615/w3-article-88020.html" },
      { label: "Ley N°19.300 · Bases Generales del Medio Ambiente", url: "https://www.bcn.cl/leychile/navegar?idNorma=30667" },
      { label: "Ley N°21.455 · Marco de Cambio Climático", url: "https://www.bcn.cl/leychile/navegar?idNorma=1177286" },
      { label: "Plan de Acción Nacional de Cambio Climático 2017-2022", url: "https://estrategia-aves.mma.gob.cl/wp-content/uploads/2023/03/MMA-2017-Plan-de-Accion-Nacional-de-Cambio-Climatico-2017-2022.pdf" },
      { label: "Plan de Adaptación al Cambio Climático en Pesca y Acuicultura", url: "https://mma.gob.cl/wp-content/uploads/2016/12/Plan-Pesca-y-Acuicultura-CMS.pdf" },
      { label: "Estrategia Nacional de Implementación de la Agenda 2030", url: "https://www.chileagenda2030.gob.cl/" },
      { label: "Ley N°19.542 · Moderniza el Sector Portuario Estatal", url: "https://www.bcn.cl/leychile/navegar?idNorma=82866" },
      { label: "Ley N°20.249 · Espacio Costero Marino de los Pueblos Originarios", url: "https://www.bcn.cl/leychile/navegar?idNorma=269291" },
      { label: "Otros decretos y reglamentos sectoriales (pesca, navegación, borde costero, concesiones marítimas, INDNR)", url: null },
    ],
  },
  {
    id: "curriculares",
    title: "Bases curriculares y programas educativos",
    items: [
      { label: "Bases Curriculares Educación Parvularia — MINEDUC (2018)", url: "https://www.curriculumnacional.cl/614/articles-69957_bases.pdf" },
      { label: "Bases Curriculares 1° a 6° Básico — MINEDUC (2018)", url: "https://www.curriculumnacional.cl/614/articles-22394_bases.pdf" },
      { label: "Bases Curriculares 6° Básico a 2° Medio — MINEDUC (2016)", url: "https://www.curriculumnacional.cl/614/articles-37136_bases.pdf" },
      { label: "Bases Curriculares 3° a 4° Medio — MINEDUC (2019)", url: "https://www.curriculumnacional.cl/614/articles-91414_bases.pdf" },
      { label: "Objetivos de aprendizaje para el ODS 14 Vida Submarina — UNESCO", url: "https://unesdoc.unesco.org/ark:/48223/pf0000252423" },
    ],
  },
  {
    id: "gobierno",
    title: "Instituciones gubernamentales relacionadas",
    items: [
      { label: "Consejo de Ministros para el Desarrollo de la Política Oceánica", url: "https://www.bcn.cl/leychile/navegar?idNorma=1171086&idParte=10299988&idVersion=2022-01-08" },
      { label: "Dirección de Medio Ambiente y Asuntos Oceánicos (DIMA / MINREL)", url: "https://www.minrel.gob.cl/minrel/direccion-de-medio-ambiente-y-asuntos-oceanicos" },
      { label: "Comité Oceanográfico Nacional (CONA)", url: "http://www.cona.cl" },
      { label: "Dirección General del Territorio Marítimo (DIRECTEMAR)", url: "https://www.directemar.cl/" },
      { label: "Subsecretaría de Pesca y Acuicultura (SUBPESCA)", url: "https://www.subpesca.cl" },
      { label: "Servicio Nacional de Pesca (SERNAPESCA)", url: "http://www.sernapesca.cl/" },
      { label: "Instituto de Fomento Pesquero (IFOP)", url: "http://www.ifop.cl" },
      { label: "INDESPA", url: "https://www.indespa.cl/" },
      { label: "Agencia Nacional de Investigación y Desarrollo (ANID)", url: "http://www.anid.cl" },
      { label: "Instituto Antártico Chileno (INACh)", url: "http://www.inach.cl" },
      { label: "Dirección Meteorológica de Chile (DMC)", url: "http://www.meteochile.cl" },
      { label: "Consejo Nacional de Implementación de la Agenda 2030", url: "https://www.chileagenda2030.gob.cl/" },
    ],
  },
  {
    id: "sociedad-civil",
    title: "Instituciones de la sociedad civil",
    items: [
      { label: "Sociedad Chilena de Ciencias del Mar (SCHCM)", url: "https://www.schcm.cl/" },
      { label: "Asociación Chilena de Periodistas para la Comunicación de la Ciencia (ACHIPEC)", url: "https://achipec.org/" },
      { label: "Asociación Chilena de Puertos y Costas", url: "https://www.puertosycostas.cl/" },
      { label: "Red de Docentes Oceánicos de Chile", url: null },
      { label: "Corporación del Patrimonio Marítimo", url: "https://patrimoniomaritimo.cl/" },
    ],
  },
  {
    id: "centros",
    title: "Centros, institutos, estaciones y laboratorios de investigación",
    intro: "Centros científicos, núcleos milenio y estaciones costeras vinculados a las ciencias del mar en Chile.",
    items: [
      { label: "COPAS Sur-Austral", url: "http://www.sur-austral.cl/" },
      { label: "COPAS Coastal", url: "https://copas-coastal.cl/" },
      { label: "Centro de Conservación Marina · Chile es Mar", url: "http://www.chileesmar.cl" },
      { label: "ESMOI — Ecología y Manejo Sustentable de Islas Oceánicas", url: "https://www.esmoi.cl/" },
      { label: "COSTA-R — Observación Marino para Riesgos del Ambiente Costero", url: "https://costar.uv.cl/" },
      { label: "INCAR — Investigación Acuícola", url: "https://www.incar.cl/es/" },
      { label: "Centro Educativo Marino · Estación Calfuco, U. Austral", url: "https://www.icml.uach.cl/estaciones/calfuco.php" },
      { label: "CIGA — Investigación GAIA Antártica", url: "http://www.umag.cl/gaiaantartica/" },
      { label: "Centro Internacional Subantártico Cabo de Hornos", url: "https://capehorncenter.com/" },
      { label: "CEQUA — Estudios del Cuaternario, Fuego-Patagonia y Antártica", url: "https://www.cequa.cl/" },
      { label: "IDEAL — Dinámica de Ecosistemas Marinos de Altas Latitudes", url: "https://www.centroideal.cl/" },
      { label: "(CR)2 — Ciencia del Clima y la Resiliencia", url: "http://www.cr2.cl/" },
      { label: "i-mar — Recursos y Ambientes Costeros", url: "https://i-mar.cl/" },
      { label: "Centro de Investigaciones Costeras (CIC)", url: "https://cic.uda.cl/" },
      { label: "CIICC — Innovación para el Cambio Climático", url: "http://www.ciicc.cl/" },
      { label: "EULA — Centro de Ciencias Ambientales, U. de Concepción", url: "http://www.eula.cl/" },
      { label: "MUSELS — Forzantes Múltiples sobre Sistemas Socio-Ecológicos Marinos", url: "http://www.eula.cl/musels/" },
      { label: "CIMARQ — Investigación Marina Quintay", url: "https://cimarq.unab.cl/" },
      { label: "CIGREN — Investigación y Gestión de Recursos Naturales", url: "https://cigren.uv.cl/" },
      { label: "CIEP — Investigación en Ecosistemas de la Patagonia", url: "http://www.ciep.cl/" },
      { label: "CIDTA — Algas y Otros Recursos Biológicos", url: "http://www.cidta-ucn.cl/es/" },
      { label: "Centro de Investigación Eutropia", url: "http://www.eutropia.cl/" },
      { label: "CREAN — Estudios de Algas Nocivas (IFOP)", url: "https://www.instagram.com/crean_ifop/?hl=es-la" },
      { label: "CESIEP — Impacto Socioeconómico de Políticas Ambientales", url: "https://www.cesiep.cl/" },
      { label: "Austral Biotech", url: "http://www.australbiotech.cl/" },
      { label: "CEAZA — Estudios Avanzados en Zonas Áridas", url: "http://www.ceaza.cl/" },
      { label: "CAPES — Applied Ecology and Sustainability", url: "http://www.capes.cl/" },
      { label: "Centro de Cambio Global UC", url: "https://cambioglobal.uc.cl/" },
      { label: "Centro Bahía Lomas", url: "http://www.bahialomas.cl/" },
      { label: "CAPIA — Acuícola y Pesquero de Investigación Aplicada", url: "http://www.capia.cl" },
      { label: "CREA — Centro Regional de Estudios Ambientales, UCSC", url: "http://www.creaucsc.cl/" },
      { label: "CIBAS — Biodiversidad y Ambientes Sustentables", url: "http://cibas.cl/" },
      { label: "CENIMA — Investigación en Medio Ambiente, UNAP", url: "https://www.unap.cl/prontus_unap/site/edic/base/port/cenima.html" },
      { label: "CIGIDEN — Gestión Integrada del Riesgo de Desastres", url: "https://www.cigiden.cl/" },
      { label: "Hémera — Centro de Observación de la Tierra", url: "https://hemera.umayor.cl/" },
      { label: "MERIC — Investigación e Innovación en Energía Marina", url: "https://www.meric.cl" },
      { label: "CIS — Investigación para la Sustentabilidad, UNAB", url: "https://vinculacion.unab.cl/servicios/cis-centro-de-investigacion-para-la-sustentabilidad/" },
      { label: "CERAM — Análisis de Recursos y Medio Ambiente", url: "http://www.pmontt.uach.cl/servicios/ceram/" },
      { label: "Instituto Milenio de Oceanografía (IMO)", url: "https://es.imo-chile.cl/" },
      { label: "SECOS — Instituto Milenio en Socio-Ecología Costera", url: "https://socioecologiacostera.cl/" },
      { label: "BASE — Biodiversidad de Ecosistemas Antárticos y Subantárticos", url: "https://www.institutobase.cl/" },
      { label: "ICML — Ciencias Marinas y Limnológicas, U. Austral", url: "http://www.icml.uach.cl/" },
      { label: "Instituto de la Patagonia, U. de Magallanes", url: "http://www.umag.cl/p.php?id=12" },
      { label: "Instituto de Ecología y Biodiversidad (IEB)", url: "https://ieb-chile.cl/" },
      { label: "INTEMIT — Tecnológico de Miticultura", url: "http://intemit.cl/" },
      { label: "Instituto Alexander von Humboldt (U. de Antofagasta)", url: "http://uantof.cl/institutos/oceanologicas" },
      { label: "INPESCA — Investigación Pesquera", url: "http://www.inpesca.cl/" },
      { label: "INTESAL — Tecnológico del Salmón", url: "https://www.intesal.cl/" },
      { label: "ECIM — Estación Costera de Investigaciones Marinas, PUC", url: "http://ecim.bio.puc.cl/es/" },
      { label: "Estación Costera Abate Juan Ignacio Molina, UCSC", url: "https://ciencias.ucsc.cl/estacion-costera/" },
      { label: "Estación Experimental Quempillén, U. Austral", url: "https://www.icml.uach.cl/estaciones/quempillen.php" },
      { label: "Biotecmar", url: "http://www.biotecmar.cl/" },
      { label: "Laboratorio de Modelación Física de Procesos Costeros", url: "https://ingenieriaoceanica.uv.cl/laboceano-2" },
      { label: "LACER — Laboratorio de Investigación Ambiental Acuático", url: "https://www.lacerupla.com/" },
      { label: "Laboratorio Limnológico Panguipulli, U. Austral", url: "https://www.icml.uach.cl/estaciones/panguipulli.php" },
      { label: "SUBELAB — Ecología Submareal, PUC", url: "https://subelab.cl/" },
      { label: "LABTOX — Toxinas Marinas, U. de Chile", url: "https://labtox.cl/" },
      { label: "ALGALAB — Estudios Algales, U. de Concepción", url: "https://www.algalab.com/" },
      { label: "ACUIGEN — Genética y Acuicultura, U. de Concepción", url: "http://www2.udec.cl/~acuigen/" },
      { label: "LOQ — Laboratorio de Oceanografía Química, U. de Concepción", url: "https://www.loq.cl/" },
      { label: "Núcleo Milenio Cyclo", url: "https://cyclosismico.cl/" },
      { label: "Núcleo Milenio Paleoclima", url: "http://www.paleoclima.cl/" },
      { label: "INVASAL — Núcleo Milenio Salmónidos Invasores", url: "https://www.iniciativamilenio.cl/invasal/" },
      { label: "UPWELL — Núcleo Milenio", url: "https://www.upwell.cl/web/" },
      { label: "NEXER — Red de Investigación en Ambientes Extremos", url: "https://www.nexerchile.cl/" },
      { label: "OSEA — Observatorio Sustentabilidad Ecosistema Acuícola", url: "https://www.ulagos.cl/2018/07/se-realiza-ceremonia-de-cierre-del-proyecto-osea-en-castro/" },
      { label: "DOCE — Departamento de Oceanografía, U. de Concepción", url: "http://oceanografia.udec.cl/" },
    ],
  },
  {
    id: "fundaciones",
    title: "Fundaciones, ONG y fondos concursables",
    items: [
      { label: "Sistema de fondos concursables del Estado", url: "https://fondos.gob.cl/" },
      { label: "ANID · Concursos", url: "https://anid.cl/concursos/" },
      { label: "FONDAP", url: "https://ayuda.anid.cl/hc/es/sections/360012314052-Fondap" },
      { label: "Programa Explora", url: "https://www.explora.cl/" },
      { label: "Fundación Mar de Chile", url: "https://www.mardechile.cl" },
      { label: "Fundación Carlos Condell", url: "https://fundacioncondell.cl" },
      { label: "Fundación Mar y Ciencia", url: "http://maryciencia.org/" },
      { label: "Fundación Oceanósfera", url: "https://www.oceanosfera.cl/" },
      { label: "Fundación Alerce", url: "http://www.ongalerce.cl" },
      { label: "Fundación Borde Costero", url: "https://bordecostero.org/" },
      { label: "Fundación CIDEMAR", url: "https://www.cidemar.com/" },
      { label: "Filantropía Cortés Solari", url: "https://www.filantropiacortessolari.cl/" },
      { label: "Fundación MERI (Melimoyu Ecosystem Research Institute)", url: "https://fundacionmeri.cl/" },
      { label: "Fundación Caserta", url: "https://caserta.cl/" },
      { label: "Fundación Valve", url: "https://fundacionvalve.org/" },
      { label: "Fundación San Ignacio de Huinay", url: "https://www.fundacionhuinay.com/" },
      { label: "FIPA — Fondo de Investigación Pesquera y Acuicultura", url: "https://www.subpesca.cl/fipa/613/w3-channel.html" },
      { label: "Oceana Chile", url: "https://chile.oceana.org/" },
      { label: "Chilemio", url: "https://www.magicochilemio.cl/" },
      { label: "Expedición Batiscafo", url: "https://www.instagram.com/expedicion_batiscafo/" },
      { label: "Academia de Exploradores Marinos", url: "https://www.instagram.com/exploradores.marinos/" },
      { label: "ONG Panthalassa", url: "https://www.instagram.com/ong_panthalassa/" },
      { label: "ONG Lamara", url: "https://lamaraong.cl/" },
      { label: "ONG Surgencia", url: "https://surgenciaong.org/" },
      { label: "ONG Oikonos", url: "https://www.oikonos.org/es" },
      { label: "ONG Qarapara", url: "https://www.qarapara.cl/" },
      { label: "ONG Patagonia Mar y Tierra", url: "http://patagoniamarytierra.cl/" },
      { label: "ONG YAQU PACHA Chile", url: "https://www.yaqupachachile.com/" },
      { label: "ONG ECOMAR Chile", url: "https://www.instagram.com/ecomar_chile/" },
      { label: "ONG Conectar para Conservar", url: "https://www.instagram.com/ongconectarparaconservar/?hl=es-la" },
      { label: "ONG Jáukén", url: "https://www.instagram.com/jauken.ong/?hl=es" },
      { label: "Sustainable Ocean Alliance Chile", url: "https://www.instagram.com/soa_chile/" },
      { label: "Océanos Prehistóricos", url: "https://www.instagram.com/oceanos_prehistoricos/" },
      { label: "Yecos del Inco", url: "https://www.instagram.com/yecosdelinco/" },
      { label: "CSIRO Chile", url: "https://www.csiro.cl/" },
      { label: "Sumérgete", url: "http://www.sumergete.cl/" },
      { label: "Acción Azul", url: "https://accionazul.org/" },
      { label: "World Wildlife Fund Chile (WWF)", url: "https://www.wwf.cl/" },
      { label: "PEW Chile", url: "https://www.pewtrusts.org/" },
      { label: "Litoral Chileno", url: "https://www.instagram.com/litoralchileno/?hl=es-la" },
    ],
  },
  {
    id: "internacional",
    title: "Organizaciones internacionales y normativa internacional",
    items: [
      { label: "Organización Marítima Internacional (OMI)", url: "https://www.imo.org/es" },
      { label: "Universidad Marítima Internacional (WMU)", url: "https://www.wmu.se/" },
      { label: "Instituto Internacional de Derecho Marítimo (IMLI)", url: "https://imli.org/" },
      { label: "Comisión Oceanográfica Intergubernamental (IOC-UNESCO)", url: "https://ioc.unesco.org/" },
      { label: "ODS 14 — Vida Submarina, Agenda 2030 ONU", url: "https://sdgs.un.org/goals/goal14" },
      { label: "World Ocean Observatory", url: "https://www.worldoceanobservatory.org/" },
      { label: "High Level Panel for a Sustainable Ocean Economy", url: "https://oceanpanel.org/" },
      { label: "International Ocean Institute", url: "https://www.ioinst.org/" },
      { label: "Global Ocean Commission", url: "http://www.some.ox.ac.uk/research/global-ocean-commission/" },
      { label: "Because the Ocean", url: "https://www.becausetheocean.org/" },
      { label: "Blue Leaders", url: "https://www.theblueleaders.org/" },
      { label: "NOAA — National Oceanic and Atmospheric Administration", url: "https://www.noaa.gov/" },
      { label: "COSEE — Center for Ocean Science Education Excellence", url: "http://www.cosee.net/" },
      { label: "National Sea Grant College Program", url: "https://www.seagrant.noaa.gov/" },
      { label: "College of Exploration", url: "https://www.coexploration.org/" },
      { label: "National Geographic Society", url: "https://www.nationalgeographic.org/" },
      { label: "Association of Zoos and Aquariums (AZA)", url: "https://www.aza.org/about-us" },
      { label: "Lawrence Hall of Science, UC Berkeley", url: "https://www.lawrencehallofscience.org/" },
      { label: "The Ocean Project", url: "https://theoceanproject.org/" },
      { label: "Convención de las Naciones Unidas sobre el Derecho del Mar (CONVEMAR) y tratados internacionales asociados (SOLAS, MARPOL, CCAMLR, entre otros)", url: null },
    ],
  },
  {
    id: "carreras",
    title: "Carreras profesionales, técnicas, magíster y doctorados",
    intro: "Programas de educación superior en ciencias del mar dictados en universidades chilenas.",
    items: [
      { label: "Pregrado: Biología Marina, Oceanografía, Acuicultura e Ingeniería Civil Oceánica en 12 universidades chilenas (PUC, UNAB, UNAP, UACh, UCSC, UCN, UANTOF, UdeC, ULagos, UMAG, UV, PUCV)", url: null },
      { label: "Técnico de nivel superior: Acuicultura y Salmonicultura en UNAP, UC Temuco, UACh, UMAG y CFT Santo Tomás", url: null },
      { label: "17 programas de doctorado afines a ciencias del mar (Acuicultura, Biología Marina, Ciencias Antárticas, Oceanografía, Ecología y Evolución, entre otros)", url: null },
      { label: "21 programas de magíster afines a ciencias del mar (Oceanografía, Ecología Marina, Gestión Portuaria, Recursos Acuáticos, entre otros)", url: null },
    ],
  },
  {
    id: "redes-sociales",
    title: "Medios y redes sociales relacionados",
    items: [
      { label: "Mundo Marítimo", url: "https://www.mundomaritimo.cl/" },
      { label: "Agenda Marítima", url: "https://www.agendamaritima.cl" },
      { label: "Portal Portuario", url: "https://portalportuario.cl/" },
      { label: "AQUA — Acuicultura y Pesca", url: "https://www.aqua.cl/" },
      { label: "Mundo Acuícola", url: "https://www.mundoacuicola.cl/new/" },
      { label: "País Circular", url: "https://www.paiscircular.cl/" },
      { label: "Salmonexpert", url: "https://www.salmonexpert.cl/" },
      { label: "Biblioteca de los Congresos de Ciencias del Mar (SCHCM)", url: "https://www.schcm.cl/index.php/biblioteca" },
    ],
  },
  {
    id: "redes-internacionales",
    title: "Redes internacionales de educadores marinos",
    items: [
      { label: "National Marine Educators Association (NMEA), EE.UU.", url: "https://www.marine-ed.org/" },
      { label: "RELATO — Red de Educación Latinoamericana para el Océano", url: "https://relatoceano.org/" },
      { label: "IPMEN — International Pacific Marine Educators Network", url: "https://ipmen.net/" },
      { label: "EMSEA — European Marine Science Educators Association", url: "https://www.emsea.eu/" },
      { label: "CaNOE — Canadian Network for Ocean Education", url: "https://oceanliteracy.ca/" },
      { label: "Canadian Ocean Literacy Coalition", url: "https://colcoalition.ca/" },
      { label: "AMEA — Asia Marine Science Educators Association", url: "https://sites.google.com/view/asia-marine-ed/home" },
      { label: "KSFME — Korean Marine Educators Association", url: "http://english.ksfme.or.kr/" },
      { label: "MESA — Marine Education Society of Australia", url: "http://www.mesa.edu.au/" },
      { label: "AAEE — Australian Association for Environmental Education", url: "https://www.aaee.org.au/" },
      { label: "Ocean Literacy in Europe", url: "http://oceanliteracy.eu/" },
    ],
  },
  {
    id: "revistas",
    title: "Revistas y publicaciones",
    items: [
      { label: "Revista de Biología Marina y Oceanografía", url: "https://rbmo.uv.cl/es/" },
      { label: "Latin American Journal of Aquatic Research", url: "http://lajar.ucv.cl/index.php/rlajar" },
      { label: "Gayana (Oceanología y Zoología)", url: "https://gayana.cl/index.php/gn" },
      { label: "Boletín Estadístico Marítimo Anual — DIRECTEMAR", url: "https://www.directemar.cl/directemar/site/edic/base/port/boletin_maritimo.html" },
      { label: "Revista Chilena de Historia Natural", url: null },
      { label: "Andean Geology (ex Revista Geológica de Chile)", url: null },
      { label: "Revista Aqua", url: null },
      { label: "Revista de Geografía Norte Grande", url: null },
      { label: "Revista de Marina", url: null },
      { label: "Revista Mar", url: null },
      { label: "Revista Biología Pesquera, UCSC", url: null },
      { label: "Revista Investigaciones Marinas, PUCV", url: null },
    ],
  },
  {
    id: "historia-cultura",
    title: "Historia, literatura y arte oceánico de Chile",
    items: [
      { label: "Chile y el Mar — Anales de la Universidad de Chile", url: "https://anales.uchile.cl/index.php/ANUC/article/view/23555/24885" },
      { label: "El Mar en la Vida de Chile — Revista de Marina (1987)", url: "https://revistamarina.cl/revistas/1987/1/godoy.pdf" },
      { label: "El Mar en la Historia de Chile — Armada de Chile", url: "https://www.armada.cl/armada/tradicion-e-historia/archivos-historicos/el-mar-en-la-historia-de-chile/2014-05-23/124127.html" },
      { label: "Horizonte en el Pacífico: Visión Oceánica de la Armada de Chile", url: "https://www.armada.cl/custom/radio_naval/libros/libro_horizonte.pdf" },
      { label: "Narradores del mar chileno — Ediciones Universitarias de Valparaíso (1963)", url: "https://uvalibros.cl/libro/narradores-del-mar-chileno/" },
      { label: "El Mar en la Literatura chilena — Manuel Montecinos", url: null },
      { label: "Tierra de Océano — Benjamín Subercaseaux", url: null },
      { label: "Chilenos del Mar — Mariano Latorre", url: null },
      { label: "El Mar y la Literatura chilena — Claudio Solar López, Revista Mar", url: null },
      { label: "Poesía marina de Gabriela Mistral", url: null },
    ],
  },
  {
    id: "territorios",
    title: "Territorios insulares y Antártica chilena",
    items: [
      { label: "Cultura oceánica en Rapa Nui", url: "https://www.instagram.com/yilidemar/" },
      { label: "Archipiélago de Juan Fernández — Centinelas del Océano", url: "mailto:centinelasdeloceano.jf@gmail.com" },
      { label: "San Félix, San Ambrosio, Salas y Gómez, Diego Ramírez y Antártica Chilena", url: null },
    ],
  },
  {
    id: "educativos",
    title: "Recursos educativos y didácticos",
    items: [
      { label: "Las Costas de Chile — Pato Winckler", url: "http://www.patowinckler.cl/libros/" },
      { label: "RELATO · Recursos educativos", url: "https://relatoceano.org/recursos-educativos/" },
      { label: "Fundación Oceanósfera · Recursos", url: "https://www.oceanosfera.cl/recursos-1" },
      { label: "Secretos del Océano", url: "https://www.secretosdeloceano.com/" },
      { label: "El Delfín Chileno — Carla Christie, Ediciones UACh", url: "http://edicionesuach.cl/index.php/ciencias-exactas-y-naturales/238-el-delfin-chileno-carla-christie-2" },
    ],
  },
  {
    id: "monitoreo",
    title: "Monitoreo del océano",
    intro: "Plataformas de datos oceanográficos, climáticos y ambientales en Chile.",
    items: [
      { label: "Registro Nacional de Áreas Protegidas", url: "http://areasprotegidas.mma.gob.cl/" },
      { label: "POAL — Programa de Observación del Ambiente Litoral", url: "https://www.directemar.cl/directemar/site/edic/base/port/datos_poal.html" },
      { label: "CENDHOC — Centro Nacional de Datos Hidrográficos y Oceanográficos", url: "http://www.shoa.cl/n_cendhoc/" },
      { label: "CDOM — Centro de Datos Oceanográficos y Meteorológicos", url: "http://www.cdom.cl/" },
      { label: "CEAZA-Met — Red de Estaciones Meteorológicas", url: "http://www.ceazamet.cl/" },
      { label: "CHIOOS — Chilean Integrated Ocean Observing System", url: "https://chioos.cl/" },
      { label: "CHONOS — Sistema de Información Oceanográfica y Atmosférica", url: "http://chonos.ifop.cl/" },
      { label: "BiblioMIT — Recurso Mytilus chilensis", url: "https://www.bibliomit.cl/" },
      { label: "Plataforma Digital de Cambio Climático", url: "http://basedigitaldelclima.mma.gob.cl/" },
      { label: "Arclim — Atlas de Riesgos Climáticos para Chile", url: "https://arclim.mma.gob.cl/" },
    ],
  },
  {
    id: "en-construccion",
    title: "En construcción",
    intro: "Categorías del índice del GT Cultura Oceánica que aún no tienen material cargado.",
    emptyNote: "Diagrama interactivo del GT COCEAN, intereses marítimos, centros de instrucción marítima y buceo, observatorio de compromisos oceánicos, y glosario de cultura oceánica — se irán sumando a medida que estén disponibles.",
    items: [],
  },
];
